language: node_js
node_js:
- '8'
install: 
script:
- npm run test
branches:
  only:
  - master
  - dev
before_install:
- openssl aes-256-cbc -K $encrypted_195ead8d2d0a_key -iv $encrypted_195ead8d2d0a_iv
  -in client-secret.json.enc -out client-secret.json -d
