runtime: nodejs
env: flex

automatic_scaling:
    min_num_instances: 1
    max_num_instances: 4
    cool_down_period_sec: 180
    cpu_utilization:
          target_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: vegapi-197219:europe-west1:vegdb
